[hooks]
"claim.post" = ["bl-delivery", "tracker"]
"claim.pre" = ["bl-delivery"]
"close.post" = ["bl-delivery", "tracker"]
"close.pre" = ["bl-delivery"]
"create.post" = ["tracker"]
"drop.post" = ["bl-delivery", "tracker"]
"install.pre" = ["tracker"]
"prime.post" = ["bl-delivery"]
"prime.pre" = ["tracker"]
"sync.pre" = ["tracker"]
"unclaim.post" = ["bl-delivery", "tracker"]
"unclaim.pre" = ["bl-delivery"]
"update.post" = ["tracker"]
