[hooks]
"claim.post" = ["bl-delivery", "tracker"]
"close.post" = ["bl-delivery", "github-issues", "tracker"]
"close.pre" = ["bl-delivery"]
"create.post" = ["github-issues", "tracker"]
"install.pre" = ["tracker"]
"prime.post" = ["bl-delivery"]
"prime.pre" = ["tracker"]
show = ["bl-delivery"]
"sync.pre" = ["tracker"]
"unclaim.post" = ["bl-delivery", "tracker"]
"update.post" = ["github-issues", "tracker"]
